<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Kapitel 10 Regression och korrelation | R-anvisningar till Grundläggande statistik</title>
  <meta name="description" content="Kapitel 10 Regression och korrelation | R-anvisningar till Grundläggande statistik" />
  <meta name="generator" content="bookdown 0.26 and GitBook 2.6.7" />

  <meta property="og:title" content="Kapitel 10 Regression och korrelation | R-anvisningar till Grundläggande statistik" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Kapitel 10 Regression och korrelation | R-anvisningar till Grundläggande statistik" />
  
  
  



<meta name="date" content="2022-05-18" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="variansanalys.html"/>

<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">R-anvisningar</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduktion</a></li>
<li class="chapter" data-level="2" data-path="installation.html"><a href="installation.html"><i class="fa fa-check"></i><b>2</b> Installation</a>
<ul>
<li class="chapter" data-level="2.1" data-path="installation.html"><a href="installation.html#inledning"><i class="fa fa-check"></i><b>2.1</b> Inledning</a></li>
<li class="chapter" data-level="2.2" data-path="installation.html"><a href="installation.html#installation-av-r"><i class="fa fa-check"></i><b>2.2</b> Installation av R</a></li>
<li class="chapter" data-level="2.3" data-path="installation.html"><a href="installation.html#installation-av-rstudio"><i class="fa fa-check"></i><b>2.3</b> Installation av RStudio</a></li>
<li class="chapter" data-level="2.4" data-path="installation.html"><a href="installation.html#gränssnittet-i-rstudio"><i class="fa fa-check"></i><b>2.4</b> Gränssnittet i RStudio</a></li>
<li class="chapter" data-level="2.5" data-path="installation.html"><a href="installation.html#paket-i-r"><i class="fa fa-check"></i><b>2.5</b> Paket i R</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="objekt-och-funktioner.html"><a href="objekt-och-funktioner.html"><i class="fa fa-check"></i><b>3</b> Objekt och funktioner</a>
<ul>
<li class="chapter" data-level="3.1" data-path="objekt-och-funktioner.html"><a href="objekt-och-funktioner.html#sekvenser-av-funktioner"><i class="fa fa-check"></i><b>3.1</b> Sekvenser av funktioner</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="dataimport.html"><a href="dataimport.html"><i class="fa fa-check"></i><b>4</b> Dataimport</a>
<ul>
<li class="chapter" data-level="4.1" data-path="dataimport.html"><a href="dataimport.html#direkt-inskrivning-av-data"><i class="fa fa-check"></i><b>4.1</b> Direkt inskrivning av data</a></li>
<li class="chapter" data-level="4.2" data-path="dataimport.html"><a href="dataimport.html#import-från-en-extern-fil"><i class="fa fa-check"></i><b>4.2</b> Import från en extern fil</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="beskrivande-statistik.html"><a href="beskrivande-statistik.html"><i class="fa fa-check"></i><b>5</b> Beskrivande statistik</a>
<ul>
<li class="chapter" data-level="5.1" data-path="beskrivande-statistik.html"><a href="beskrivande-statistik.html#datamängd"><i class="fa fa-check"></i><b>5.1</b> Datamängd</a></li>
<li class="chapter" data-level="5.2" data-path="beskrivande-statistik.html"><a href="beskrivande-statistik.html#filtrering-av-rader-och-selektion-av-kolumner"><i class="fa fa-check"></i><b>5.2</b> Filtrering av rader och selektion av kolumner</a></li>
<li class="chapter" data-level="5.3" data-path="beskrivande-statistik.html"><a href="beskrivande-statistik.html#transformationer-av-variabler"><i class="fa fa-check"></i><b>5.3</b> Transformationer av variabler</a></li>
<li class="chapter" data-level="5.4" data-path="beskrivande-statistik.html"><a href="beskrivande-statistik.html#sammanfattande-statistik"><i class="fa fa-check"></i><b>5.4</b> Sammanfattande statistik</a></li>
<li class="chapter" data-level="5.5" data-path="beskrivande-statistik.html"><a href="beskrivande-statistik.html#grafer"><i class="fa fa-check"></i><b>5.5</b> Grafer</a></li>
<li class="chapter" data-level="5.6" data-path="beskrivande-statistik.html"><a href="beskrivande-statistik.html#övningar"><i class="fa fa-check"></i><b>5.6</b> Övningar</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="sannolikhetsfördelningar-och-slumptal.html"><a href="sannolikhetsfördelningar-och-slumptal.html"><i class="fa fa-check"></i><b>6</b> Sannolikhetsfördelningar och slumptal</a>
<ul>
<li class="chapter" data-level="6.1" data-path="sannolikhetsfördelningar-och-slumptal.html"><a href="sannolikhetsfördelningar-och-slumptal.html#fördelningar"><i class="fa fa-check"></i><b>6.1</b> Fördelningar</a></li>
<li class="chapter" data-level="6.2" data-path="sannolikhetsfördelningar-och-slumptal.html"><a href="sannolikhetsfördelningar-och-slumptal.html#egna-funktioner"><i class="fa fa-check"></i><b>6.2</b> Egna funktioner</a></li>
<li class="chapter" data-level="6.3" data-path="sannolikhetsfördelningar-och-slumptal.html"><a href="sannolikhetsfördelningar-och-slumptal.html#simuleringar"><i class="fa fa-check"></i><b>6.3</b> Simuleringar</a></li>
<li class="chapter" data-level="6.4" data-path="sannolikhetsfördelningar-och-slumptal.html"><a href="sannolikhetsfördelningar-och-slumptal.html#övningar-1"><i class="fa fa-check"></i><b>6.4</b> Övningar</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="ett-stickprov.html"><a href="ett-stickprov.html"><i class="fa fa-check"></i><b>7</b> Ett stickprov</a>
<ul>
<li class="chapter" data-level="7.1" data-path="ett-stickprov.html"><a href="ett-stickprov.html#normalfördelad-data-eller-stora-stickprov"><i class="fa fa-check"></i><b>7.1</b> Normalfördelad data (eller stora stickprov)</a></li>
<li class="chapter" data-level="7.2" data-path="ett-stickprov.html"><a href="ett-stickprov.html#binär-data.-proportioner"><i class="fa fa-check"></i><b>7.2</b> Binär data. Proportioner</a></li>
<li class="chapter" data-level="7.3" data-path="ett-stickprov.html"><a href="ett-stickprov.html#nominal-eller-ordinal-data.-goodness-of-fit"><i class="fa fa-check"></i><b>7.3</b> Nominal eller ordinal data. Goodness-of-fit</a></li>
<li class="chapter" data-level="7.4" data-path="ett-stickprov.html"><a href="ett-stickprov.html#övningar-2"><i class="fa fa-check"></i><b>7.4</b> Övningar</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="två-stickprov.html"><a href="två-stickprov.html"><i class="fa fa-check"></i><b>8</b> Två stickprov</a>
<ul>
<li class="chapter" data-level="8.1" data-path="två-stickprov.html"><a href="två-stickprov.html#normalfördelad-data-eller-stora-stickprov-1"><i class="fa fa-check"></i><b>8.1</b> Normalfördelad data (eller stora stickprov)</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="två-stickprov.html"><a href="två-stickprov.html#t-test-för-två-matchade-stickprov"><i class="fa fa-check"></i><b>8.1.1</b> t-test för två matchade stickprov</a></li>
<li class="chapter" data-level="8.1.2" data-path="två-stickprov.html"><a href="två-stickprov.html#t-test-för-två-oberoende-stickprov"><i class="fa fa-check"></i><b>8.1.2</b> t-test för två oberoende stickprov</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="två-stickprov.html"><a href="två-stickprov.html#binär-data.-proportioner-1"><i class="fa fa-check"></i><b>8.2</b> Binär data. Proportioner</a></li>
<li class="chapter" data-level="8.3" data-path="två-stickprov.html"><a href="två-stickprov.html#nominal-eller-ordinal-data.-korstabeller"><i class="fa fa-check"></i><b>8.3</b> Nominal eller ordinal data. Korstabeller</a></li>
<li class="chapter" data-level="8.4" data-path="två-stickprov.html"><a href="två-stickprov.html#övningar-3"><i class="fa fa-check"></i><b>8.4</b> Övningar</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="variansanalys.html"><a href="variansanalys.html"><i class="fa fa-check"></i><b>9</b> Variansanalys</a>
<ul>
<li class="chapter" data-level="9.1" data-path="variansanalys.html"><a href="variansanalys.html#variansanalys.-en-faktor"><i class="fa fa-check"></i><b>9.1</b> Variansanalys. En faktor</a></li>
<li class="chapter" data-level="9.2" data-path="variansanalys.html"><a href="variansanalys.html#variansanalys.-en-faktor-med-block"><i class="fa fa-check"></i><b>9.2</b> Variansanalys. En faktor med block</a></li>
<li class="chapter" data-level="9.3" data-path="variansanalys.html"><a href="variansanalys.html#variansanalys.-två-faktorer-med-block"><i class="fa fa-check"></i><b>9.3</b> Variansanalys. Två faktorer med block</a></li>
<li class="chapter" data-level="9.4" data-path="variansanalys.html"><a href="variansanalys.html#övningar-4"><i class="fa fa-check"></i><b>9.4</b> Övningar</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="regression-och-korrelation.html"><a href="regression-och-korrelation.html"><i class="fa fa-check"></i><b>10</b> Regression och korrelation</a>
<ul>
<li class="chapter" data-level="10.1" data-path="regression-och-korrelation.html"><a href="regression-och-korrelation.html#regression"><i class="fa fa-check"></i><b>10.1</b> Regression</a></li>
<li class="chapter" data-level="10.2" data-path="regression-och-korrelation.html"><a href="regression-och-korrelation.html#korrelation"><i class="fa fa-check"></i><b>10.2</b> Korrelation</a></li>
<li class="chapter" data-level="10.3" data-path="regression-och-korrelation.html"><a href="regression-och-korrelation.html#övningar-5"><i class="fa fa-check"></i><b>10.3</b> Övningar</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">R-anvisningar till <em>Grundläggande statistik</em></a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="regression-och-korrelation" class="section level1 hasAnchor" number="10">
<h1><span class="header-section-number">Kapitel 10</span> Regression och korrelation<a href="regression-och-korrelation.html#regression-och-korrelation" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>Regression och korrelation är metoder för att mäta ett samband mellan två kontinuerliga variabler. Regression skattar en variabel som en funktion av en annan, t.ex. kan man skatta en modell av en plantas höjd som en funktion av näringsinnehåll i marken. Korrelation är ett mått på samvariation mellan två variabler.</p>
<div id="regression" class="section level2 hasAnchor" number="10.1">
<h2><span class="header-section-number">10.1</span> Regression<a href="regression-och-korrelation.html#regression" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>I en regression modelleras en variabel som en funktion av en annan variabel. Vid enkel linjär regression finns <em>en</em> sådan <em>förklarande variabel</em> och förhållandet mellan variablerna antas vara linjärt. Modellen kan uttryckas</p>
<p><span class="math display">\[y_{i} = \beta_0 + \beta_1 x_i + \varepsilon_i,\]</span></p>
<p>där <span class="math inline">\(y_i\)</span> är observation <span class="math inline">\(i\)</span> av den förklarade variabeln, <span class="math inline">\(\beta_0\)</span> och <span class="math inline">\(\beta_1\)</span> är parametrar, <span class="math inline">\(x_i\)</span> är observation <span class="math inline">\(i\)</span> av den förklarande variabeln, och <span class="math inline">\(\varepsilon_i\)</span> är en slumpmässig felterm.</p>
<p>Ta som exempel data på förväntad medellivslängd och bnp per capita. Datan hämtas från <code>gapminder</code>-paketet. Paketet <code>ggrepel</code> kan användas för att sätta punktetiketter som inte överlappar. För enklare tolkning av modellen transformeras bnp per capita till att vara i tusen dollar, snarare än dollar.</p>
<div class="sourceCode" id="cb370"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb370-1"><a href="regression-och-korrelation.html#cb370-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gapminder)</span>
<span id="cb370-2"><a href="regression-och-korrelation.html#cb370-2" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> gapminder <span class="sc">%&gt;%</span> </span>
<span id="cb370-3"><a href="regression-och-korrelation.html#cb370-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(year <span class="sc">==</span> <span class="dv">2007</span>, continent <span class="sc">==</span> <span class="st">&quot;Europe&quot;</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb370-4"><a href="regression-och-korrelation.html#cb370-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">gdpPercap =</span> gdpPercap <span class="sc">/</span> <span class="dv">1000</span>)</span>
<span id="cb370-5"><a href="regression-och-korrelation.html#cb370-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb370-6"><a href="regression-och-korrelation.html#cb370-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggrepel)</span>
<span id="cb370-7"><a href="regression-och-korrelation.html#cb370-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(dat, <span class="fu">aes</span>(gdpPercap, lifeExp)) <span class="sc">+</span></span>
<span id="cb370-8"><a href="regression-och-korrelation.html#cb370-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb370-9"><a href="regression-och-korrelation.html#cb370-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text_repel</span>(<span class="fu">aes</span>(<span class="at">label =</span> country), <span class="at">size =</span> <span class="dv">3</span>)</span></code></pre></div>
<p><img src="R-anvisningar_files/figure-html/unnamed-chunk-223-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>Datan visar ett positivt samband mellan variablerna - högre bnp per capita är kopplat till högre medelllivslängd. En regressionmodell kan i R skattas med <code>lm</code>-funktionen. Syntaxen är väldigt lik den för anovamodellen, men istället för en faktor som förklarande variabel används nu en kontinuerlig variabel.</p>
<div class="sourceCode" id="cb371"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb371-1"><a href="regression-och-korrelation.html#cb371-1" aria-hidden="true" tabindex="-1"></a>mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(lifeExp <span class="sc">~</span> gdpPercap, <span class="at">data =</span> dat)</span>
<span id="cb371-2"><a href="regression-och-korrelation.html#cb371-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb371-3"><a href="regression-och-korrelation.html#cb371-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = lifeExp ~ gdpPercap, data = dat)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -2.79839 -1.30472  0.00807  1.33443  2.87766 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 72.27106    0.69416 104.113  &lt; 2e-16 ***
## gdpPercap    0.21463    0.02514   8.537  2.8e-09 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.598 on 28 degrees of freedom
## Multiple R-squared:  0.7225, Adjusted R-squared:  0.7125 
## F-statistic: 72.88 on 1 and 28 DF,  p-value: 2.795e-09</code></pre>
<p>Funktionen <code>summary</code> ger en sammanfattning av modellen. Skattningen av parametern <span class="math inline">\(\beta_0\)</span> ges som raden <code>(Intercept)</code> och dess tolkning är som förväntat värde i medellivslängd om bnp per capita är noll. Det är ofta lutningsparametern som är mer intressant. Skattningen av <span class="math inline">\(\beta_1\)</span> ges på den rad som har samma namn som den förklarande variabeln, här <code>gdpPercap</code>. Den skattade parametern är <span class="math inline">\(0.2146\)</span>. Lutningsparametern har den generella tolkning som ökningen i y-variabeln när x-variabeln ökar med 1. I det här fallet ger <span class="math inline">\(0.2146\)</span> att ett lands medellivslängd ökar med ungefär 78 dagar när bnp per capita ökar med 1000 dollar.</p>
<p>Man kan rita ut regressionlinjen i en graf med <code>geom_smooth</code> och argumentet <code>method</code> satt till <code>"lm"</code>.</p>
<div class="sourceCode" id="cb373"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb373-1"><a href="regression-och-korrelation.html#cb373-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(dat, <span class="fu">aes</span>(gdpPercap, lifeExp)) <span class="sc">+</span></span>
<span id="cb373-2"><a href="regression-och-korrelation.html#cb373-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb373-3"><a href="regression-och-korrelation.html#cb373-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> lm)</span></code></pre></div>
<p><img src="R-anvisningar_files/figure-html/unnamed-chunk-225-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>Den blå linjen illustrerar regressionlinjen <span class="math inline">\(72.27 + 0.2146 \cdot x\)</span>. Det grå bandet kring linjen är ett konfidensintervall för skattningen av y-variabeln vid ett visst x-värde.</p>
<p>Utskriften från <code>summary</code> ger också tester av parametrarna (den högra kolumnen <code>Pr(&gt;|t|)</code> ger p-värdet för ett test där nollhypotesen är att populationsparametern är noll). I det här fallet är både intercept och lutning skilda från noll. Motsvarande F-test för lutningen kan tas fram med en anova-tabell.</p>
<div class="sourceCode" id="cb374"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb374-1"><a href="regression-och-korrelation.html#cb374-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb374-2"><a href="regression-och-korrelation.html#cb374-2" aria-hidden="true" tabindex="-1"></a><span class="fu">Anova</span>(mod)</span></code></pre></div>
<pre><code>## Anova Table (Type II tests)
## 
## Response: lifeExp
##            Sum Sq Df F value    Pr(&gt;F)    
## gdpPercap 186.031  1  72.883 2.795e-09 ***
## Residuals  71.469 28                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Testerna av en regressionmodell bygger på ett normalfördelningsantagande oh ett antagande om homoskedasticitet (lika varians i y oavsett position på x-axeln). Antagandena kan undersökas genom att titta på skattningens <em>residualer</em> - skillnaden mellan det faktiska y-värdet och modellens värde. Residualerna kan undersökas med ett histogram eller en QQ-plot. En annan vanlig diagnosplot är ett spridningsdiagram med skattade värden på x-axeln och residualerna på y-axeln.</p>
<div class="sourceCode" id="cb376"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb376-1"><a href="regression-och-korrelation.html#cb376-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(<span class="fu">residuals</span>(mod), <span class="at">breaks =</span> <span class="dv">10</span>)</span>
<span id="cb376-2"><a href="regression-och-korrelation.html#cb376-2" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(<span class="fu">residuals</span>(mod)); <span class="fu">qqline</span>(<span class="fu">residuals</span>(mod))</span>
<span id="cb376-3"><a href="regression-och-korrelation.html#cb376-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">residuals</span>(mod) <span class="sc">~</span> <span class="fu">fitted</span>(mod))</span></code></pre></div>
<p><img src="R-anvisningar_files/figure-html/unnamed-chunk-228-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>Om data följer en normalfördelning bör histogrammet visa en ungefärlig normalkurva, QQ-plotten bör visa punkter på den diagonala linjen och spridningsdiagrammet bör visa en slumpmässig spridning av punkter. Graferna pekar i det här fallet inte på några tydliga avvikelser från normalfördelningsantagandet, möjligen pekar QQ-plotten på mindre spridning i svansarna än en teoretisk normalfördelning.</p>
</div>
<div id="korrelation" class="section level2 hasAnchor" number="10.2">
<h2><span class="header-section-number">10.2</span> Korrelation<a href="regression-och-korrelation.html#korrelation" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Korrelation ger ett mått mellan <span class="math inline">\(-1\)</span> och <span class="math inline">\(1\)</span> på hur väl två variabler samvarierar. En korrelation över noll tyder på ett positivt samband mellan variablerna - en observation med ett högt värde i den ena variabeln har också ett högt värde på den andra - medan en korrelation under noll tyder på ett negativt samband. I R kan korrelation beräknas med <code>cor</code> och två variabler som första och andra argument. Funktionen <code>cor.test</code> ger ett test där nollhypotesen är att korrelationen är noll.</p>
<div class="sourceCode" id="cb377"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb377-1"><a href="regression-och-korrelation.html#cb377-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(dat<span class="sc">$</span>lifeExp, dat<span class="sc">$</span>gdpPercap)</span></code></pre></div>
<pre><code>## [1] 0.8499711</code></pre>
<div class="sourceCode" id="cb379"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb379-1"><a href="regression-och-korrelation.html#cb379-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(dat<span class="sc">$</span>lifeExp, dat<span class="sc">$</span>gdpPercap)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  dat$lifeExp and dat$gdpPercap
## t = 8.5372, df = 28, p-value = 2.795e-09
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.7058444 0.9265221
## sample estimates:
##       cor 
## 0.8499711</code></pre>
<p>Medellivslängd och bnp per capita har en stark positiv korrelation på <span class="math inline">\(0.85\)</span> och den korrelation är signifikant skild från noll (<span class="math inline">\(p = 2.795 \cdot 10^{-9}\)</span>). Notera att p-värdet är detsamma som testet av lutningsparametern i regressionen.</p>

</div>
<div id="övningar-5" class="section level2 hasAnchor" number="10.3">
<h2><span class="header-section-number">10.3</span> Övningar<a href="regression-och-korrelation.html#övningar-5" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="exercise">
<p><span id="exr:unlabeled-div-73" class="exercise"><strong>Övning 10.1  (Blodtryck) </strong></span>Följande fascinerande blodtrycksdata hämtas från kvinnor i Sala.</p>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:right;">
Ålder
</th>
<th style="text-align:right;">
Blodtryck
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
32
</td>
<td style="text-align:right;">
115
</td>
</tr>
<tr>
<td style="text-align:right;">
35
</td>
<td style="text-align:right;">
112
</td>
</tr>
<tr>
<td style="text-align:right;">
47
</td>
<td style="text-align:right;">
120
</td>
</tr>
<tr>
<td style="text-align:right;">
50
</td>
<td style="text-align:right;">
136
</td>
</tr>
<tr>
<td style="text-align:right;">
55
</td>
<td style="text-align:right;">
144
</td>
</tr>
<tr>
<td style="text-align:right;">
60
</td>
<td style="text-align:right;">
160
</td>
</tr>
<tr>
<td style="text-align:right;">
62
</td>
<td style="text-align:right;">
144
</td>
</tr>
<tr>
<td style="text-align:right;">
64
</td>
<td style="text-align:right;">
156
</td>
</tr>
<tr>
<td style="text-align:right;">
70
</td>
<td style="text-align:right;">
169
</td>
</tr>
<tr>
<td style="text-align:right;">
75
</td>
<td style="text-align:right;">
164
</td>
</tr>
</tbody>
</table>
<p>a. Skatta en enkel linjär regressionsmodell och tolka lutningskoefficienten i termer av de ursprungliga variablerna.</p>
<p>b. Beräkna ett konfidensintervall för lutningskoefficienten.</p>
<p>c. Undersök modellens antaganden (normalfördelade residualer, lika varians för skilda nivåer av x-variabeln).</p>
<p>d. Testa om lutningskoefficienten är skild från 1.</p>
</div>
<div class="hypothesis">
<p><span id="hyp:unlabeled-div-74" class="hypothesis"><strong>Lösningsförslag 10.1  (Blodtryck) </strong></span>Data kan läsas in från excelfilen med uppgiftsdata. Två kontinuerliga variabler kan enklast illustreras med ett spridningsdiagram.</p>
<div class="sourceCode" id="cb381"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb381-1"><a href="regression-och-korrelation.html#cb381-1" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">&quot;Data/Uppgiftsdata.xlsx&quot;</span>, <span class="at">sheet =</span> <span class="st">&quot;Blodtryck&quot;</span>)</span>
<span id="cb381-2"><a href="regression-och-korrelation.html#cb381-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb381-3"><a href="regression-och-korrelation.html#cb381-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(dat, <span class="fu">aes</span>(Ålder, Blodtryck)) <span class="sc">+</span></span>
<span id="cb381-4"><a href="regression-och-korrelation.html#cb381-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb381-5"><a href="regression-och-korrelation.html#cb381-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> lm)</span></code></pre></div>
<p><img src="R-anvisningar_files/figure-html/unnamed-chunk-231-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>Det finns ett tydligt positivt samband mellan variablerna.</p>
<div class="sourceCode" id="cb382"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb382-1"><a href="regression-och-korrelation.html#cb382-1" aria-hidden="true" tabindex="-1"></a>mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(Blodtryck <span class="sc">~</span> Ålder, dat)</span>
<span id="cb382-2"><a href="regression-och-korrelation.html#cb382-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Blodtryck ~ Ålder, data = dat)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -10.868  -4.915   1.217   4.254  11.042 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  65.4650     9.5384   6.863 0.000129 ***
## Ålder         1.3915     0.1685   8.259 3.47e-05 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 7.145 on 8 degrees of freedom
## Multiple R-squared:  0.895,  Adjusted R-squared:  0.8819 
## F-statistic: 68.21 on 1 and 8 DF,  p-value: 3.47e-05</code></pre>
<p>Regressionslinjen ges av <span class="math inline">\(y = 65.465 + 1.3915\)</span>.</p>
<p>a. Blodtrycket ökar med <span class="math inline">\(1.39\)</span> för varje ökat år.</p>
<p>b. Ett konfidensintervall kan tas fram med <code>confint</code>.</p>
<div class="sourceCode" id="cb384"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb384-1"><a href="regression-och-korrelation.html#cb384-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(mod)</span></code></pre></div>
<pre><code>##                 2.5 %    97.5 %
## (Intercept) 43.469261 87.460661
## Ålder        1.003005  1.780088</code></pre>
<p>Ett 95-procentigt konfidensintervall för lutning ges av <span class="math inline">\((1.003, 1.780)\)</span>.</p>
<p>c. Modellen bygger på normalfördelade residualer och lika varians för skilda nivåer av ålder.</p>
<div class="sourceCode" id="cb386"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb386-1"><a href="regression-och-korrelation.html#cb386-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">residuals</span>(mod) <span class="sc">~</span> <span class="fu">fitted</span>(mod))</span></code></pre></div>
<p><img src="R-anvisningar_files/figure-html/unnamed-chunk-234-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>Det finns inga extremvärden bland residualer och inga tydliga tecken på skillnader i varians.</p>
<p>d. Eftersom 1 ligger precis utanför ett 95-procentigt konfidensintervall, bör ett test på femprocentsnivån leda till att man förkastar nollhypotesen att lutningen är 1. Detta kan testas formellt genom <code>emtrends</code> från paketet <code>emmeans</code>.</p>
<div class="sourceCode" id="cb387"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb387-1"><a href="regression-och-korrelation.html#cb387-1" aria-hidden="true" tabindex="-1"></a><span class="fu">test</span>(<span class="fu">emtrends</span>(mod, <span class="sc">~</span> <span class="dv">1</span>, <span class="st">&quot;Ålder&quot;</span>), <span class="at">null =</span> <span class="dv">1</span>)</span></code></pre></div>
<pre><code>##  1       Ålder.trend    SE df null t.ratio p.value
##  overall        1.39 0.168  8    1   2.324  0.0486</code></pre>
<p>P-värdet ligger precis under fem procent.</p>
</div>
<div class="exercise">
<p><span id="exr:unlabeled-div-75" class="exercise"><strong>Övning 10.2  (Metodjämförelse) </strong></span>Någon vill jämföra två metoder för att mäta volym på någon planta. Hen mäter därför nio olika plantor med bägge metoderna, vilket ger följande värden.</p>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
Metod
</th>
<th style="text-align:right;">
1
</th>
<th style="text-align:right;">
2
</th>
<th style="text-align:right;">
3
</th>
<th style="text-align:right;">
4
</th>
<th style="text-align:right;">
5
</th>
<th style="text-align:right;">
6
</th>
<th style="text-align:right;">
7
</th>
<th style="text-align:right;">
8
</th>
<th style="text-align:right;">
9
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
A
</td>
<td style="text-align:right;">
701
</td>
<td style="text-align:right;">
707
</td>
<td style="text-align:right;">
768
</td>
<td style="text-align:right;">
714
</td>
<td style="text-align:right;">
712
</td>
<td style="text-align:right;">
684
</td>
<td style="text-align:right;">
716
</td>
<td style="text-align:right;">
751
</td>
<td style="text-align:right;">
674
</td>
</tr>
<tr>
<td style="text-align:left;">
B
</td>
<td style="text-align:right;">
935
</td>
<td style="text-align:right;">
989
</td>
<td style="text-align:right;">
924
</td>
<td style="text-align:right;">
904
</td>
<td style="text-align:right;">
924
</td>
<td style="text-align:right;">
975
</td>
<td style="text-align:right;">
889
</td>
<td style="text-align:right;">
948
</td>
<td style="text-align:right;">
904
</td>
</tr>
</tbody>
</table>
<p>a. Illustrera datan med en lämplig figur. Testa med ett lämpligt test om metoderna ger samma medelvärdesvolym.</p>
<p>b. Beräkna korrelationen mellan metoderna. Metod A är en dyrare men bättre metod. Ger mätning med metod B en säker uppskattning av utfallet med metod A?</p>
</div>
<div class="hypothesis">
<p><span id="hyp:unlabeled-div-76" class="hypothesis"><strong>Lösningsförslag 10.2  (Metodjämförelse) </strong></span>Data kan hämtas från excelfilen med uppgiftsdata. Ett diagram visar en tydlig skillnad mellan grupperna.</p>
<div class="sourceCode" id="cb389"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb389-1"><a href="regression-och-korrelation.html#cb389-1" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">&quot;Data/Uppgiftsdata.xlsx&quot;</span>, <span class="at">sheet =</span> <span class="st">&quot;Metodjämförelse&quot;</span>)</span>
<span id="cb389-2"><a href="regression-och-korrelation.html#cb389-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb389-3"><a href="regression-och-korrelation.html#cb389-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(dat, <span class="fu">aes</span>(Metod, Volym, <span class="at">group =</span> Yta)) <span class="sc">+</span></span>
<span id="cb389-4"><a href="regression-och-korrelation.html#cb389-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb389-5"><a href="regression-och-korrelation.html#cb389-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>()</span></code></pre></div>
<p><img src="R-anvisningar_files/figure-html/unnamed-chunk-237-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>a. Ibland behöver man inget test.</p>
<p>Men en jämförelse mellan två grupper kan förstås tas som ett parat t-test. Man kan först använda <code>pivot_wider</code> för att skriva om data till kolumnform.</p>
<div class="sourceCode" id="cb390"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb390-1"><a href="regression-och-korrelation.html#cb390-1" aria-hidden="true" tabindex="-1"></a>dat_wide <span class="ot">&lt;-</span> dat <span class="sc">%&gt;%</span> </span>
<span id="cb390-2"><a href="regression-och-korrelation.html#cb390-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> Metod, <span class="at">values_from =</span> Volym)</span>
<span id="cb390-3"><a href="regression-och-korrelation.html#cb390-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb390-4"><a href="regression-och-korrelation.html#cb390-4" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(dat_wide<span class="sc">$</span>A, dat_wide<span class="sc">$</span>B, <span class="at">paired =</span> T)</span></code></pre></div>
<pre><code>## 
##  Paired t-test
## 
## data:  dat_wide$A and dat_wide$B
## t = -14.228, df = 8, p-value = 5.8e-07
## alternative hypothesis: true mean difference is not equal to 0
## 95 percent confidence interval:
##  -253.7192 -182.9475
## sample estimates:
## mean difference 
##       -218.3333</code></pre>
<p>Parad data kan också ses som det enklaste exemplet på ett block, och analyseras som en anova med block. För att R ska tolka variabeln Yta som en faktor kan man ändra dess typ med <code>as.character</code>.</p>
<div class="sourceCode" id="cb392"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb392-1"><a href="regression-och-korrelation.html#cb392-1" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> dat <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">Yta =</span> <span class="fu">as.character</span>(Yta))</span>
<span id="cb392-2"><a href="regression-och-korrelation.html#cb392-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb392-3"><a href="regression-och-korrelation.html#cb392-3" aria-hidden="true" tabindex="-1"></a>mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(Volym <span class="sc">~</span> Metod <span class="sc">+</span> Yta, dat)</span>
<span id="cb392-4"><a href="regression-och-korrelation.html#cb392-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb392-5"><a href="regression-och-korrelation.html#cb392-5" aria-hidden="true" tabindex="-1"></a><span class="fu">Anova</span>(mod)</span></code></pre></div>
<pre><code>## Anova Table (Type II tests)
## 
## Response: Volym
##           Sum Sq Df  F value  Pr(&gt;F)    
## Metod     214512  1 202.4419 5.8e-07 ***
## Yta         7440  8   0.8777  0.5709    
## Residuals   8477  8                     
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>P-värdet från ett F-test på metod är detsamma som det från det parade t-testet.</p>
<p>b.</p>
<div class="sourceCode" id="cb394"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb394-1"><a href="regression-och-korrelation.html#cb394-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(dat_wide, <span class="fu">aes</span>(B, A)) <span class="sc">+</span> </span>
<span id="cb394-2"><a href="regression-och-korrelation.html#cb394-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()</span></code></pre></div>
<p><img src="R-anvisningar_files/figure-html/unnamed-chunk-240-1.png" width="672" style="display: block; margin: auto;" /></p>
<div class="sourceCode" id="cb395"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb395-1"><a href="regression-och-korrelation.html#cb395-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(dat_wide<span class="sc">$</span>A, dat_wide<span class="sc">$</span>B)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  dat_wide$A and dat_wide$B
## t = -0.17396, df = 7, p-value = 0.8668
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  -0.6992626  0.6257789
## sample estimates:
##         cor 
## -0.06560983</code></pre>
<p>Det finns inget signifikant samband mellan metoderna. Mätning med metod B säger alltså inget om utfallet i metod A. Om metod A är den mer precisa metoden, tyder detta på att metod B inte bör användas.</p>
</div>
<div class="exercise">
<p><span id="exr:unlabeled-div-77" class="exercise"><strong>Övning 10.3  (Anscombes data) </strong></span>Den raka regressionslinjen eller det enkla korrelationsmåttet säger lite om hur data egentligen ser ut. En vanlig illustration av detta är <em>Anscombes kvartett</em>, fyra exempel konstruerade av den brittiske statistikern Francis Anscombe 1973. Datan finns tillgänglig i R som datasetet <code>anscombe</code>. Plotta de fyra graferna (<code>x1</code> paras med <code>y1</code> och så vidare) i spridningsdiagram och beräkna korrelation för varje par. Kommentera utfallet.</p>
</div>
<div class="hypothesis">
<p><span id="hyp:unlabeled-div-78" class="hypothesis"><strong>Lösningsförslag 10.3  (Anscombes data) </strong></span>Data finns tillgänglig i R som <code>anscombe</code>, vilket är en tabell med åtta kolumner som består av fyra par (där <code>x1</code> är kopplad till <code>y1</code> och så vidare). Paren kan plottas med enkla spridningsdiagram.</p>
<div class="sourceCode" id="cb397"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb397-1"><a href="regression-och-korrelation.html#cb397-1" aria-hidden="true" tabindex="-1"></a>g1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(anscombe, <span class="fu">aes</span>(x1, y1)) <span class="sc">+</span> <span class="fu">geom_point</span>()</span>
<span id="cb397-2"><a href="regression-och-korrelation.html#cb397-2" aria-hidden="true" tabindex="-1"></a>g2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(anscombe, <span class="fu">aes</span>(x2, y2)) <span class="sc">+</span> <span class="fu">geom_point</span>()</span>
<span id="cb397-3"><a href="regression-och-korrelation.html#cb397-3" aria-hidden="true" tabindex="-1"></a>g3 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(anscombe, <span class="fu">aes</span>(x3, y3)) <span class="sc">+</span> <span class="fu">geom_point</span>()</span>
<span id="cb397-4"><a href="regression-och-korrelation.html#cb397-4" aria-hidden="true" tabindex="-1"></a>g4 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(anscombe, <span class="fu">aes</span>(x4, y4)) <span class="sc">+</span> <span class="fu">geom_point</span>()</span>
<span id="cb397-5"><a href="regression-och-korrelation.html#cb397-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb397-6"><a href="regression-och-korrelation.html#cb397-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(patchwork)</span>
<span id="cb397-7"><a href="regression-och-korrelation.html#cb397-7" aria-hidden="true" tabindex="-1"></a>(g1 <span class="sc">+</span> g2) <span class="sc">/</span> (g3 <span class="sc">+</span> g4)</span></code></pre></div>
<p><img src="R-anvisningar_files/figure-html/unnamed-chunk-241-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>Graferna ser olika ut.</p>
<div class="sourceCode" id="cb398"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb398-1"><a href="regression-och-korrelation.html#cb398-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(anscombe<span class="sc">$</span>x1, anscombe<span class="sc">$</span>y1)</span></code></pre></div>
<pre><code>## [1] 0.8164205</code></pre>
<div class="sourceCode" id="cb400"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb400-1"><a href="regression-och-korrelation.html#cb400-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(anscombe<span class="sc">$</span>x2, anscombe<span class="sc">$</span>y2)</span></code></pre></div>
<pre><code>## [1] 0.8162365</code></pre>
<div class="sourceCode" id="cb402"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb402-1"><a href="regression-och-korrelation.html#cb402-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(anscombe<span class="sc">$</span>x3, anscombe<span class="sc">$</span>y3)</span></code></pre></div>
<pre><code>## [1] 0.8162867</code></pre>
<div class="sourceCode" id="cb404"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb404-1"><a href="regression-och-korrelation.html#cb404-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(anscombe<span class="sc">$</span>x4, anscombe<span class="sc">$</span>y4)</span></code></pre></div>
<pre><code>## [1] 0.8165214</code></pre>
<p>Men har samma korrelation (till fjärde decimal).</p>
<p>En modern utveckling av Anscombes kvartett ges av <em>The Datasaurus Dozen</em>.</p>
</div>
<div class="exercise">
<p><span id="exr:unlabeled-div-79" class="exercise"><strong>Övning 10.4  (Beach 2050) </strong></span>Bland kursdata finns en fil med uppmätta temperaturer vid väderstationen i Falsterbo. Den kan läsas in från csv-filen. Se tidigare uppgift om beskrivande statistik för detaljer.</p>
<div class="sourceCode" id="cb406"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb406-1"><a href="regression-och-korrelation.html#cb406-1" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> <span class="fu">read_csv2</span>(<span class="st">&quot;Data/smhi-opendata_1_52230_20210912_114534.csv&quot;</span>, <span class="at">skip =</span> <span class="dv">9</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb406-2"><a href="regression-och-korrelation.html#cb406-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Lufttemperatur =</span> <span class="fu">as.numeric</span>(Lufttemperatur))</span></code></pre></div>
<p>En sammanställning av medeltemperaturer de senaste fyrtio åren ges av följande tabell.</p>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:right;">
År
</th>
<th style="text-align:right;">
Medeltemperatur
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
1981
</td>
<td style="text-align:right;">
7.92
</td>
</tr>
<tr>
<td style="text-align:right;">
1982
</td>
<td style="text-align:right;">
8.53
</td>
</tr>
<tr>
<td style="text-align:right;">
1983
</td>
<td style="text-align:right;">
9.03
</td>
</tr>
<tr>
<td style="text-align:right;">
1984
</td>
<td style="text-align:right;">
8.38
</td>
</tr>
<tr>
<td style="text-align:right;">
1985
</td>
<td style="text-align:right;">
6.61
</td>
</tr>
<tr>
<td style="text-align:right;">
1986
</td>
<td style="text-align:right;">
7.20
</td>
</tr>
<tr>
<td style="text-align:right;">
1987
</td>
<td style="text-align:right;">
6.60
</td>
</tr>
<tr>
<td style="text-align:right;">
1988
</td>
<td style="text-align:right;">
8.76
</td>
</tr>
<tr>
<td style="text-align:right;">
1989
</td>
<td style="text-align:right;">
9.76
</td>
</tr>
<tr>
<td style="text-align:right;">
1990
</td>
<td style="text-align:right;">
9.91
</td>
</tr>
<tr>
<td style="text-align:right;">
1991
</td>
<td style="text-align:right;">
8.61
</td>
</tr>
<tr>
<td style="text-align:right;">
1992
</td>
<td style="text-align:right;">
9.55
</td>
</tr>
<tr>
<td style="text-align:right;">
1993
</td>
<td style="text-align:right;">
8.12
</td>
</tr>
<tr>
<td style="text-align:right;">
1994
</td>
<td style="text-align:right;">
9.26
</td>
</tr>
<tr>
<td style="text-align:right;">
1995
</td>
<td style="text-align:right;">
9.00
</td>
</tr>
<tr>
<td style="text-align:right;">
1996
</td>
<td style="text-align:right;">
7.32
</td>
</tr>
<tr>
<td style="text-align:right;">
1997
</td>
<td style="text-align:right;">
8.99
</td>
</tr>
<tr>
<td style="text-align:right;">
1998
</td>
<td style="text-align:right;">
8.58
</td>
</tr>
<tr>
<td style="text-align:right;">
1999
</td>
<td style="text-align:right;">
9.29
</td>
</tr>
<tr>
<td style="text-align:right;">
2000
</td>
<td style="text-align:right;">
9.72
</td>
</tr>
<tr>
<td style="text-align:right;">
2001
</td>
<td style="text-align:right;">
8.98
</td>
</tr>
<tr>
<td style="text-align:right;">
2002
</td>
<td style="text-align:right;">
9.51
</td>
</tr>
<tr>
<td style="text-align:right;">
2003
</td>
<td style="text-align:right;">
8.89
</td>
</tr>
<tr>
<td style="text-align:right;">
2004
</td>
<td style="text-align:right;">
8.92
</td>
</tr>
<tr>
<td style="text-align:right;">
2005
</td>
<td style="text-align:right;">
9.01
</td>
</tr>
<tr>
<td style="text-align:right;">
2006
</td>
<td style="text-align:right;">
9.63
</td>
</tr>
<tr>
<td style="text-align:right;">
2007
</td>
<td style="text-align:right;">
9.80
</td>
</tr>
<tr>
<td style="text-align:right;">
2008
</td>
<td style="text-align:right;">
9.81
</td>
</tr>
<tr>
<td style="text-align:right;">
2009
</td>
<td style="text-align:right;">
9.17
</td>
</tr>
<tr>
<td style="text-align:right;">
2010
</td>
<td style="text-align:right;">
7.79
</td>
</tr>
<tr>
<td style="text-align:right;">
2011
</td>
<td style="text-align:right;">
9.37
</td>
</tr>
<tr>
<td style="text-align:right;">
2012
</td>
<td style="text-align:right;">
9.20
</td>
</tr>
<tr>
<td style="text-align:right;">
2013
</td>
<td style="text-align:right;">
10.08
</td>
</tr>
<tr>
<td style="text-align:right;">
2014
</td>
<td style="text-align:right;">
11.53
</td>
</tr>
<tr>
<td style="text-align:right;">
2015
</td>
<td style="text-align:right;">
10.73
</td>
</tr>
<tr>
<td style="text-align:right;">
2016
</td>
<td style="text-align:right;">
10.58
</td>
</tr>
<tr>
<td style="text-align:right;">
2017
</td>
<td style="text-align:right;">
10.24
</td>
</tr>
<tr>
<td style="text-align:right;">
2018
</td>
<td style="text-align:right;">
11.42
</td>
</tr>
<tr>
<td style="text-align:right;">
2019
</td>
<td style="text-align:right;">
11.36
</td>
</tr>
<tr>
<td style="text-align:right;">
2020
</td>
<td style="text-align:right;">
11.44
</td>
</tr>
</tbody>
</table>
<p>a. Skapa en passande graf med år på x-axeln och medeltemperatur på y-axeln. I ggplot kan en skattad regressionlinje illustreras genom <code>geom_smooth(method = lm)</code>.</p>
<p>b. Skatta en regressionsmodell med år som förklarande variabel och medeltemperatur som förklarad variabel. Genomför ett t-test eller F-test för att se om lutningskoefficienten är skild från noll.</p>
<p>c. Funktionen <code>predict</code> kan användas för att skapa en skattning av populationsmedelvärdet för valfritt värde på den förklarande variabeln. Titta på hjälpsidan för <code>predict.lm</code> och använd funktionen för att förutsäga medeltemperatur för varje år fram till 2050. Illustrera skattningarna i en passande graf.</p>
<p>d. Vilken kritik finns mot den här modellen?</p>
</div>
<div class="hypothesis">
<p><span id="hyp:unlabeled-div-80" class="hypothesis"><strong>Lösningsförslag 10.4  (Beach 2050) </strong></span>Data läses in med koden i uppgiften.</p>
<div class="sourceCode" id="cb407"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb407-1"><a href="regression-och-korrelation.html#cb407-1" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> <span class="fu">read_csv2</span>(<span class="st">&quot;Data/smhi-opendata_1_52230_20210912_114534.csv&quot;</span>, <span class="at">skip =</span> <span class="dv">9</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb407-2"><a href="regression-och-korrelation.html#cb407-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Lufttemperatur =</span> <span class="fu">as.numeric</span>(Lufttemperatur))</span></code></pre></div>
<p>Årsmedelvärden kan beräknas genom att skapa en variabel för År med <code>year</code> från paketet <code>lubridate</code>. Därefter grupperas efter år och summeras med medelvärdet. Slutligen filteras datan för att ta fram de senaste 40 åren. Datan sparas under namnet <code>dat_medel</code>.</p>
<div class="sourceCode" id="cb408"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb408-1"><a href="regression-och-korrelation.html#cb408-1" aria-hidden="true" tabindex="-1"></a>dat_medel <span class="ot">&lt;-</span> dat <span class="sc">%&gt;%</span> </span>
<span id="cb408-2"><a href="regression-och-korrelation.html#cb408-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(Å<span class="at">r =</span> lubridate<span class="sc">::</span><span class="fu">year</span>(Datum)) <span class="sc">%&gt;%</span> </span>
<span id="cb408-3"><a href="regression-och-korrelation.html#cb408-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(År) <span class="sc">%&gt;%</span> </span>
<span id="cb408-4"><a href="regression-och-korrelation.html#cb408-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Medeltemperatur =</span> <span class="fu">mean</span>(Lufttemperatur)) <span class="sc">%&gt;%</span> </span>
<span id="cb408-5"><a href="regression-och-korrelation.html#cb408-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(År <span class="sc">&gt;</span> <span class="dv">1980</span>, År <span class="sc">&lt;</span> <span class="dv">2021</span>)</span></code></pre></div>
<p>a. Tidsdata illustreras ofta med en linjediagram. Regressionslinjen kan skapas med <code>geom_smooth(method = lm)</code>.</p>
<div class="sourceCode" id="cb409"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb409-1"><a href="regression-och-korrelation.html#cb409-1" aria-hidden="true" tabindex="-1"></a>g1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(dat_medel, <span class="fu">aes</span>(År, Medeltemperatur)) <span class="sc">+</span> </span>
<span id="cb409-2"><a href="regression-och-korrelation.html#cb409-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span> </span>
<span id="cb409-3"><a href="regression-och-korrelation.html#cb409-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb409-4"><a href="regression-och-korrelation.html#cb409-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> lm)</span>
<span id="cb409-5"><a href="regression-och-korrelation.html#cb409-5" aria-hidden="true" tabindex="-1"></a>g1</span></code></pre></div>
<p><img src="R-anvisningar_files/figure-html/unnamed-chunk-247-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>Det finns tecken på en ökning över tid.</p>
<p>b. Regressionmodellen skattas med funktionen <code>lm</code>. Medeltemperatur är den förklarade variabeln och år den förklarande - regressionsformeln skrivs därmed <code>Medeltemperatur ~ År</code>. Modellen har automatiskt ett intercept, men man hade även kunnat skriva <code>Medeltemperatur ~ 1 + År</code> för tydlighet. Resultatet skrivs ut med <code>summary</code>.</p>
<div class="sourceCode" id="cb410"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb410-1"><a href="regression-och-korrelation.html#cb410-1" aria-hidden="true" tabindex="-1"></a>mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(Medeltemperatur <span class="sc">~</span> År, dat_medel)</span>
<span id="cb410-2"><a href="regression-och-korrelation.html#cb410-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Medeltemperatur ~ År, data = dat_medel)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -2.1256 -0.5387  0.1005  0.5267  1.4678 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -138.63357   23.31584  -5.946 6.75e-07 ***
## År             0.07391    0.01165   6.341 1.94e-07 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.8509 on 38 degrees of freedom
## Multiple R-squared:  0.5141, Adjusted R-squared:  0.5014 
## F-statistic: 40.21 on 1 and 38 DF,  p-value: 1.939e-07</code></pre>
<p>Linjen har ett intercept på <span class="math inline">\(-138.63\)</span> och en lutning på <span class="math inline">\(0.074\)</span>. Standardtolkningar är att det var <span class="math inline">\(-138\)</span> grader år noll (hmmmm) och att medeltemperaturen ökar med <span class="math inline">\(0.07\)</span> grader per år.</p>
<p>Testet för lutningen (ett t-test) ges på raden för <code>År</code>. Nollhypotesen är att lutningskoefficienten är 0 och det låga p-värdet tyder på att den nollhypotesen bör förkastas. Det finns en statistiskt säkerställd ökning i medeltemperatur över tid.</p>
<p>Diagnosgrafer ger inga uppenbara avvikelser från normalfördelning eller struktur i spridningen.</p>
<div class="sourceCode" id="cb412"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb412-1"><a href="regression-och-korrelation.html#cb412-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(<span class="fu">residuals</span>(mod))</span>
<span id="cb412-2"><a href="regression-och-korrelation.html#cb412-2" aria-hidden="true" tabindex="-1"></a><span class="fu">qqline</span>(<span class="fu">residuals</span>(mod))</span></code></pre></div>
<p><img src="R-anvisningar_files/figure-html/unnamed-chunk-249-1.png" width="672" style="display: block; margin: auto;" /></p>
<div class="sourceCode" id="cb413"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb413-1"><a href="regression-och-korrelation.html#cb413-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">fitted</span>(mod), <span class="fu">residuals</span>(mod))</span></code></pre></div>
<p><img src="R-anvisningar_files/figure-html/unnamed-chunk-249-2.png" width="672" style="display: block; margin: auto;" /></p>
<p>c. Det är möjligt att prognosticera värden med <code>predict</code>. Funktionen tar en skattad modell (här <code>mod</code>) och en ny datatabellen, som innehåller en kolumn med samma namn som den förklarande variabeln i modellen (här <code>År</code>). Funktionen kan även producera konfidensintervall för skattningen, här genom <code>interval = "conf"</code> för ett konfidensintervall.</p>
<div class="sourceCode" id="cb414"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb414-1"><a href="regression-och-korrelation.html#cb414-1" aria-hidden="true" tabindex="-1"></a>dat_predict <span class="ot">&lt;-</span> <span class="fu">predict</span>(mod, <span class="at">newdata =</span> <span class="fu">tibble</span>(Å<span class="at">r =</span> <span class="dv">2020</span><span class="sc">:</span><span class="dv">2050</span>), <span class="at">interval =</span> <span class="st">&quot;conf&quot;</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb414-2"><a href="regression-och-korrelation.html#cb414-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_tibble</span>() <span class="sc">%&gt;%</span> <span class="co"># Ändra till en tibble för enklare hantering</span></span>
<span id="cb414-3"><a href="regression-och-korrelation.html#cb414-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(Å<span class="at">r =</span> <span class="dv">2020</span><span class="sc">:</span><span class="dv">2050</span>) <span class="co"># Lägg till år för senare graf</span></span>
<span id="cb414-4"><a href="regression-och-korrelation.html#cb414-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb414-5"><a href="regression-och-korrelation.html#cb414-5" aria-hidden="true" tabindex="-1"></a>g1 <span class="sc">+</span> <span class="co"># Samma grundgraf som tidigare</span></span>
<span id="cb414-6"><a href="regression-och-korrelation.html#cb414-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(År, fit), <span class="at">data =</span> dat_predict) <span class="sc">+</span> <span class="co"># Lägger till en linje för skattningar för kommande år</span></span>
<span id="cb414-7"><a href="regression-och-korrelation.html#cb414-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="fu">aes</span>(År, <span class="at">ymin =</span> lwr, <span class="at">ymax =</span> upr),  <span class="co"># Lägger till ett band för konfidensintervallet för skattningen</span></span>
<span id="cb414-8"><a href="regression-och-korrelation.html#cb414-8" aria-hidden="true" tabindex="-1"></a>              <span class="at">inherit.aes =</span> F, <span class="at">data =</span> dat_predict,</span>
<span id="cb414-9"><a href="regression-och-korrelation.html#cb414-9" aria-hidden="true" tabindex="-1"></a>              <span class="at">alpha =</span> <span class="fl">0.2</span>, <span class="at">fill =</span> <span class="st">&quot;red&quot;</span>) <span class="co"># alpha sätter genomskinlighet för en yta</span></span></code></pre></div>
<p><img src="R-anvisningar_files/figure-html/unnamed-chunk-250-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>d. I en tidigare uppgift påpekas att data inte samlats in samma tider på dygnet under hela mätperioden - det är därmed möjligt att den observerade ökningen beror på förändringar i mätmetod. Valet av de fyrtio senaste åren var ett godtyckligt val som påverkar lutningen kraftigt (till exempel om man av en ren slump börjar med några kalla år och avslutar med några varma). Regressionsmodellen är en linjär modell, vilket ger den uppenbarligen orimliga tolkning av interceptet som en temperatur år 0.</p>
<p>Slutligen finns förstås det grundläggande problemet med prognoser: det kan ske oväntade saker som leder till strukturbrott och gör att sambandet mellan förklarande och förklarad variabel förändras.</p>
</div>
<div class="exercise">
<p><span id="exr:unlabeled-div-81" class="exercise"><strong>Övning 10.5  (Datasaurus Dozen) </strong></span>Datasaurus-datan är en konstruerad datamängd som illustrerar hur skilda mönster i data kan ge samma punktskattningar (medelvärden, standardavvikelser och korrelationer). Datan finns tillgänglig som en del av TidyTuesday-projektet och kan hämtas med följande rad.</p>
<div class="sourceCode" id="cb415"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb415-1"><a href="regression-och-korrelation.html#cb415-1" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> readr<span class="sc">::</span><span class="fu">read_csv</span>(<span class="st">&#39;https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-10-13/datasaurus.csv&#39;</span>)</span></code></pre></div>
<p>a. Datan innehåller en gruppering (<code>dataset</code>) och x- och y-koordinater. För varje grupp i kolumnen <code>dataset</code>, beräkna medelvärde och standardavvikelse för x och y, och beräkna korrelationen mellan x och y. Kommentera utfallet.</p>
<p>b. Illustrera materialet med en lämplig graf, t.ex. ett spridningsdiagram mellan x och y för varje grupp i kolumnen <code>dataset</code>.</p>
</div>
<div class="hypothesis">
<p><span id="hyp:unlabeled-div-82" class="hypothesis"><strong>Lösningsförslag 10.5  (Datasaurus Dozen) </strong></span>a. Punkskattningar kan beräknas genom att gruppera enligt <code>dataset</code> och summera med lämpliga funktioner (<code>mean</code>, <code>sd</code> och <code>cor</code>).</p>
<div class="sourceCode" id="cb416"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb416-1"><a href="regression-och-korrelation.html#cb416-1" aria-hidden="true" tabindex="-1"></a>dat <span class="sc">%&gt;%</span></span>
<span id="cb416-2"><a href="regression-och-korrelation.html#cb416-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(dataset) <span class="sc">%&gt;%</span> </span>
<span id="cb416-3"><a href="regression-och-korrelation.html#cb416-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="fu">mean</span>(x), <span class="fu">mean</span>(y), <span class="fu">sd</span>(x), <span class="fu">sd</span>(y), <span class="fu">cor</span>(x,y))</span></code></pre></div>
<pre><code>## # A tibble: 13 × 6
##    dataset    `mean(x)` `mean(y)` `sd(x)` `sd(y)` `cor(x, y)`
##    &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;       &lt;dbl&gt;
##  1 away            54.3      47.8    16.8    26.9     -0.0641
##  2 bullseye        54.3      47.8    16.8    26.9     -0.0686
##  3 circle          54.3      47.8    16.8    26.9     -0.0683
##  4 dino            54.3      47.8    16.8    26.9     -0.0645
##  5 dots            54.3      47.8    16.8    26.9     -0.0603
##  6 h_lines         54.3      47.8    16.8    26.9     -0.0617
##  7 high_lines      54.3      47.8    16.8    26.9     -0.0685
##  8 slant_down      54.3      47.8    16.8    26.9     -0.0690
##  9 slant_up        54.3      47.8    16.8    26.9     -0.0686
## 10 star            54.3      47.8    16.8    26.9     -0.0630
## 11 v_lines         54.3      47.8    16.8    26.9     -0.0694
## 12 wide_lines      54.3      47.8    16.8    26.9     -0.0666
## 13 x_shape         54.3      47.8    16.8    26.9     -0.0656</code></pre>
<p>Grupperna har samma medelvärde och standardavvikelser i x och y. Korrelationerna mellan x och y är mycket lika.</p>
<p>b. Datan kan illustreras med ett spridningsdiagram. Funktionen <code>facet_wrap</code> kan användas för separata fönster för skilda grupper.</p>
<div class="sourceCode" id="cb418"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb418-1"><a href="regression-och-korrelation.html#cb418-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(dat, <span class="fu">aes</span>(x, y)) <span class="sc">+</span></span>
<span id="cb418-2"><a href="regression-och-korrelation.html#cb418-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb418-3"><a href="regression-och-korrelation.html#cb418-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> dataset)</span></code></pre></div>
<p><img src="R-anvisningar_files/figure-html/unnamed-chunk-253-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>Figuren visar att det finns tydliga mönster i flera av grupperna och tydliga skillnader mellan dem.</p>
</div>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="variansanalys.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "sepia",
"family": "serif",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["R-anvisningar.pdf"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
